version: "3.9"

services: 

  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web
    ports: 
      - "8005:8005"
    # environment: 
      # - DEBUG=1
      # - DJANGO_ALLOWED_HOSTS=['*']
      # - NGINX_ENTRYPOINT_QUIET_LOGS=1  # включает лог старта контейнера
    env_file:
      - .env
    volumes:
      - .:/usr/src/app/
      - ./backend/static/:/static
      - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
   
      